### ISSUE TITLE
propTypes issues

### ISSUE THREAD

**Issue by cbjs** [9gag-open-source/react-native-snackbar-dialog#33]
![screenshot_1507779287](https://user-images.githubusercontent.com/1215843/31478223-61b33c20-af41-11e7-877c-6cfa03be353a.png)

**Comment by eduardoperez2151** [comment]
Same Error +1

**Comment by raymondctc** [comment]
Which react native versions are you guys using?

**Comment by eduardoperez2151** [comment]
"react-native": "^0.47.2",

**Comment by foggy1** [comment]
+1 @raymondctc any word on this? Trying to upgrade to 0.51 of react, wasn't having issues on 0.48.2

**Comment by foggy1** [comment]
@raymondctc @eduardoperez2151 @cbjs I found the issue, I'm not sure how best to resolve the root problem.

`Object.defineProperty(module.exports,'babelPluginFlowReactPropTypes_proptype_SnackItemType',{value:require('react').PropTypes.shape({title:require('react').PropTypes.string.isRequired,id:require('react').PropTypes.string,confirmText:require('react').PropTypes.string,onConfirm:require('react').PropTypes.func,cancelText:require('react').PropTypes.string,onCancel:require('react').PropTypes.func,style:require('react').PropTypes.object,backgroundColor:require('react').PropTypes.string,buttonColor:require('react').PropTypes.string,textColor:require('react').PropTypes.string,position:require('react').PropTypes.oneOf(['bottom','top']),onAutoDismiss:require('react').PropTypes.func,fadeOutDuration:require('react').PropTypes.number,duration:require('react').PropTypes.number,isStatic:require('react').PropTypes.bool,tapToClose:require('react').PropTypes.bool,renderContent:require('react').PropTypes.func})});](url)`

When that babel transpiler packages the SnackItemType, it does so by pulling PropTypes out of the react library: but PropTypes is a standalone library now. I got it to stop throwing up by including the new library (`var PropTypes = require('prop-types')`) and deleting all of the require('react') instances. I'll have to see if there's some setting on that babel transpiler to forego this or something.

**Comment by foggy1** [comment]
This is fixed in #34

**Comment by raymondctc** [comment]
Merged #36

**Comment by kontinuity** [comment]
Still getting this error on `"react-native-snackbar-dialog": "^1.4.1",`

**Comment by peterchibunna** [comment]
Got this error. 
`"react-native-snackbar-dialog": "^1.4.1",`
`"react-native": "0.54.4",`
